name: "publish"
on: [push]

jobs:
  api:
    runs-on: ubuntu-latest
    name: Run Dotnet Tests
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{  secrets.DOCKER_PASSWORD  }}
      GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")
      GIT_BRANCH: ${GITHUB_REF##*/}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - name: Run Tests
        run: dotnet test

      - name: Sanity Build
        run: dotnet build

      - name: Login into Docker
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Images
        run: |
          docker build -t $DOCKER_USERNAME/ipd-core:latest  -f docker/Core.Dockerfile .
          docker build -t $DOCKER_USERNAME/ipd-worker:latest -f docker/Worker.Dockerfile .

      - name: Push Images
        run: |
          docker push $DOCKER_USERNAME/ipd-core:latest
          docker push $DOCKER_USERNAME/ipd-worker:latest
