name: 'test'
on: [ push, pull_request ]

jobs:
  backend:
    runs-on: windows-latest
    name: Run Dotnet Tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Run Tests
        run: dotnet test
      - name: Sanity Build
        run: dotnet build

